package org.example.models.tracker;

public enum ActionType {
    CREATE_BUDGET,
    UPDATE_BUDGET,
    DELETE_BUDGET,
    CREATE_EXPENSE,
    UPDATE_EXPENSE,
    DELETE_EXPENSE,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,
    CREATE_BUDGET_ACCESS,
    UPDATE_BUDGET_ACCESS,
    DELETE_BUDGET_ACCESS,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER
}
